import { cn } from "../utils/utils";
import { FAQItem } from "./FAQItem";

interface Props {
  className?: string
}
export const FAQs = ({className}: Props) => {
  const classes = cn("relative gap-16 grid auto-rows-min grid-cols-1 w-full mx-auto overflow-hidden", className);

  const items = [
    {
      id: 1,
      title: "How does SUB1 achieve cooling efficiency?",
      description: "Our use of free-air and evaporative cooling systems (with optional DLC) dramatically reduces power consumption compared to traditional compressor-based systems, with additional power generated by onsite solar PV."
    },
    {
      id: 2, 
      title: "How does this efficiency aid SUB1 customers?",
      description: "Enhanced cooling efficiency leads to significant reductions in electricity use, slashing the total cost of ownership for our clients by approximately 50% compared to standard retail colocation with metered power."
    }, 
    {
      id: 3,
      title: "What are the benefits of using brownfield sites?",
      description: "Utilising brownfield sites accelerates data centre deployment by bypassing lengthy planning and build phases, leveraging existing infrastructure for quicker operational readiness and minimal community disruption."
    },
    {
      id: 4,
      title: "Are these sites available to lease or buy?",
      description: "We offer flexible ownership options, allowing customers to either lease for long-term stability or purchase outright, depending on their strategic needs."
    },
    {
      id: 5,
      title: "What's being done to reduce the environmental impact?",
      description: "Our commitment to sustainability is demonstrated through the reduced electricity consumption and minimised use of greenfield sites. Additionally, our backup generators are exclusively fuelled by HVO, significantly cutting carbon emissions during normal operations."
    }
  ]

  return (
    <div className={classes}>
      

      <div className=" grid grid-cols-1 md:grid-cols-2 gap-y-10 lg:grid-cols-2 md:gap-x-6 xl:gap-x-10">
        {
          items.map((faqItem) => {
            return (
              <FAQItem key={faqItem.id} title={faqItem.title} description={faqItem.description} />
            )
          })
        }
        <a href="#contact" className="md:flex hidden md:place-self-center md:self-start justify-center  bg-slate-200  text-primaryDark py-3 pl-4 pr-4 text-base font-semibold w-[300px] rounded-lg">More Questions?</a>
      </div>

    </div>
  )
}